reviews/urls.py
from django.conf.urls import url
from reviews import views

urlpatterns = [
    # ex: /
    url(r"^$", views.review_list, name="review_list"),
    # ex: /review/5/
    url(r"^review/(?P<review_id>[0-9]+)/$", views.review_detail, name="review_detail"),
    # ex: /wine/
    url(r"^wine$", views.wine_list, name="wine_list"),
    # ex: /wine/5/
    url(r"^wine/(?P<wine_id>[0-9]+)/$", views.wine_detail, name="wine_detail"),
    url(r"^wine/(?P<wine_id>[0-9]+)/add_review/$", views.add_review, name="add_review"),
    # ex: /review/user - get reviews for the logged user
    url(
        r"^review/user/(?P<username>\w+)/$",
        views.user_review_list,
        name="user_review_list",
    ),
    # ex: /review/user - get reviews for the user passed in the url
    url(r"^review/user/$", views.user_review_list, name="user_review_list"),
    # ex: /recommendation - get wine recommendations for the logged user
    url(
        r"^recommendation/$",
        views.user_recommendation_list,
        name="user_recommendation_list",
    ),
]

wineboiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from reviews import views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", auth_views.login, name="login"),
    url(
        r"^logout/$",
        auth_views.logout,
        {"next_page": "/", "template_name": "registration/logout.html"},
        name="logout",
    ),
    url(r"^reviews/", include("reviews.urls", namespace="reviews")),
    url(r"^register/$", views.signup, name="register"),
]

reviews/models.py
from django.db import models
import numpy as np
from django.contrib.auth.models import User

# Create your models here.


class Wine(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        return int(np.mean(all_ratings))

    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))

    wine = models.ForeignKey(Wine)
    pub_date = models.DateTimeField("date_published")
    user_name = models.CharField(max_length=100)
    comments = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)


class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "comments"]
        widgets = {"comments": Textarea(attrs={"cols": 40, "rows": 15})}

reviews/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from reviews.models import Review, Wine, Cluster
from reviews.forms import ReviewForm
from reviews.suggestions import update_clusters
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
import datetime
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("/reviews")
    else:
        form = UserCreationForm()
    return render(request, "registration/registration_form.html", {"form": form})


def review_list(request):
    latest_review_list = Review.objects.order_by("-pub_date")[:9]
    context = {"latest_review_list": latest_review_list}
    return render(request, "reviews/review_list.html", context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    print(review.comments)
    return render(request, "reviews/review_detail.html", {"review": review})


def wine_list(request):
    wine_list = Wine.objects.order_by("-name")
    context = {"wine_list": wine_list}
    return render(request, "reviews/wine_list.html", context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    return render(request, "reviews/wine_detail.html", {"wine": wine, "form": form})


@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data["rating"]
        print(rating)
        print(form.cleaned_data)
        comment = form.cleaned_data["comments"]

        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comments = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("reviews:wine_detail", args=(wine.id,)))

    return render(request, "reviews/wine_detail.html", {"wine": wine, "form": form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by("-pub_date")
    context = {"latest_review_list": latest_review_list, "username": username}
    return render(request, "reviews/user_review_list.html", context)


@login_required
def user_recommendation_list(request):
    # get request user reviewed wines
    user_reviews = Review.objects.filter(
        user_name=request.user.username
    ).prefetch_related("wine")
    user_reviews_wine_ids = set(map(lambda x: x.wine.id, user_reviews))

    # get request user cluster name (just the first one right now)
    try:
        user_cluster_name = (
            User.objects.get(username=request.user.username).cluster_set.first().name
        )
    except:  # if no cluster assigned for a user, update clusters
        update_clusters()
        user_cluster_name = (
            User.objects.get(username=request.user.username).cluster_set.first().name
        )

    # get usernames for other members of the cluster
    user_cluster_other_members = (
        Cluster.objects.get(name=user_cluster_name)
        .users.exclude(username=request.user.username)
        .all()
    )
    other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    # get reviews by those users, excluding wines reviewed by the request user
    other_users_reviews = Review.objects.filter(
        user_name__in=other_members_usernames
    ).exclude(wine__id__in=user_reviews_wine_ids)
    other_users_reviews_wine_ids = set(map(lambda x: x.wine.id, other_users_reviews))

    # then get a wine list including the previous IDs, order by rating
    wine_list = sorted(
        list(Wine.objects.filter(id__in=other_users_reviews_wine_ids)),
        key=lambda x: x.average_rating,
        reverse=True,
    )

    print(wine_list)

    return render(
        request,
        "reviews/user_recommendation_list.html",
        {"username": request.user.username, "wine_list": wine_list},
    )

reviews/templates/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>La Bodega</title>


    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/cards.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  <body>

    <header>
      <div class="logo">

        {% if user.is_authenticated %}
          <a href="{% url 'reviews:review_list' %}">La Bodega</a>
        {% else %}
          <a href="{% url 'login' %}">La Bodega</a>
        {% endif %}
      </div>

      <div class="links">
        <a href="{% url 'reviews:wine_list' %}">Wine List</a>
      </div>

      {% if user.is_authenticated %}
        <div class="account">
          <a href="{% url 'reviews:user_review_list' user.username %}">Hello, <strong>admin</strong></a>
          <a href="{% url 'reviews:user_recommendation_list' %}">Wine Suggestions</a>
          <a href="{% url 'logout' %}">Logout</a>
        </div>
      {% else %}
        <div class="account">
          <a href="{% url 'login' %}">Login</a>
          <a href="{% url 'register' %}">Register</a>
        </div>
      {% endif %}
    </header>


      {% block content %}

      {% endblock %}
  </body>
</html>

templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load times %}

{% block content %}

  <link rel="stylesheet" href="{% static 'assets/css/review.css'%}">

<h2 class="heading">{{ review.wine.name }}</h2>

<section>


  <div class="star-rating" data-star="5">

    {% for i in review.rating|times %}
      <i class="fa fa-star" aria-hidden="true"></i>
    {%endfor%}

  </div>

  <div class="review">
    By <strong>{{ review.user_name }}</strong>
  </div>

  <div class="time">
    {{ review.pub_date }}
  </div>

  <div class="comment">
    {{ review.comments }}
  </div>

</section>

{% endblock %}

templates/reviews/review_list.html
{% extends 'base.html' %}
{% load static %}
{% load times %}

{% block content %}

  <link rel="stylesheet" href="{% static 'assets/css/latest_wine.css'%}">

<h2 class="heading">Latest Reviews</h2>

<section>

  {% if latest_review_list %}
    {% for review in latest_review_list %}
      <div class="card">
        <a href="{% url 'reviews:review_detail' review.id %}">
          <h2>{{ review.wine.name }}</h2>

          <div class="star-rating" data-star="5">
            {% for i in review.rating|times %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {%endfor%}
          </div>
          <div class="reviews">
            By <strong>{{ review.user_name }}</strong>
          </div>

        </a>
      </div>
      {% endfor %}
  {% else %}
  <p>No reviews are available.</p>
  {% endif %}

</section>


{% endblock %}

templates/reviews/user_recommendation_list.html
{% extends 'base.html' %}
{% load static %}
{% load times %}

{% block content %}

  <link rel="stylesheet" href="{% static 'assets/css/latest_wine.css'%}">

<h2 class="heading">Suggestions for {{ username }}</h2>

<section>

  {% if latest_review_list %}
    {% for review in latest_review_list %}
      <div class="card">
        <a href="{% url 'reviews:review_detail' review.id %}">
          <h2>{{ review.wine.name }}</h2>

          <div class="star-rating" data-star="5">
            {% for i in review.rating|times %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {%endfor%}
          </div>
          <div class="reviews">
            By <strong>{{ review.user_name }}</strong>
          </div>

        </a>
      </div>
      {% endfor %}
  {% else %}
  <p>No reviews are available.</p>
  {% endif %}

</section>


{% endblock %}

templates/reviews/user_review_list.html
{% extends 'base.html' %}
{% load static %}
{% load times %}

{% block content %}

  <link rel="stylesheet" href="{% static 'assets/css/latest_wine.css'%}">

<h2 class="heading">Reviews by {{ username }}</h2>

<section>

  {% if latest_review_list %}
    {% for review in latest_review_list %}
      <div class="card">
        <a href="{% url 'reviews:review_detail' review.id %}">
          <h2>{{ review.wine.name }}</h2>

          <div class="star-rating" data-star="5">
            {% for i in review.rating|times %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {%endfor%}
          </div>
          <div class="reviews">
            By <strong>{{ review.user_name }}</strong>
          </div>

        </a>
      </div>
      {% endfor %}
  {% else %}
  <p>No reviews are available.</p>
  {% endif %}

</section>


{% endblock %}

templates/reviews/wine_detail.html
{% extends 'base.html'%}
{% load static %}
{% load times %}

{% block content %}

<h2 class="heading">{{ wine.name }}</h2>

<section>

  <link rel="stylesheet" href="{% static 'assets/css/wine.css'%}">

  <div class="star-rating" data-star="5">

    {% for i in wine.average_rating|times %}
      <i class="fa fa-star" aria-hidden="true"></i>
    {%endfor%}

  </div>

  <div class="reviews">
    {{ wine.review_set.count }} Reviews
  </div>


  <h3>Recent reviews</h3>
  <div class="recent">

    <section>

      {% if wine.review_set.all %}
      {% for review in wine.review_set.all %}
      <div class="card">
        <a href="{% url 'reviews:review_detail' review.id %}">
          <p>{{ review.comments }}</p>

          <div class="star-rating" data-star="5">
            {% for i in review.rating|times %}
              <i class="fa fa-star" aria-hidden="true"></i>
            {% endfor %}
          </div>
          <div class="reviews">
            By <strong>{{ review.user_name }}</strong>
          </div>

        </a>
      </div>
      {% endfor %}
      {% else %}
      <p>No reviews for this wine yet</p>
      {% endif %}



</section>

{% if user.is_authenticated %}
<div>


<h3>Add your review</h3>

<br>

<div class="add-review">

  <form action="{% url 'reviews:add_review' wine.id %}" method="post" >
    {% csrf_token %}

<label for="star">Rate :</label>
  <select class="star" name="rating">
    <option value="0">0</option>
    <option value="0">1</option>
    <option value="0">2</option>
    <option value="0">3</option>
    <option value="0">4</option>
    <option value="0">5</option>
  </select>
  <br>
  <br>

  <textarea name="comments" placeholder="comments"></textarea>
<br>

  <input type="submit" name="button" value="Submit">

  </form>
</div>
</div>
{% endif %}



{% endblock %}

templates/reviews/wine_list.html
{% extends 'base.html' %}
{% load static %}
{% load times %}

{% block content %}

<link rel="stylesheet" href="{% static 'assets/css/wine_list.css' %}">

  <h2 class="heading">Wine List</h2>

  {% if wine_list %}
    <section>

      {% for wine in wine_list %}
        <div class="card">
          <a href="{% url 'reviews:wine_detail' wine.id %}">
            <h2>{{ wine.name }}</h2>
            <div class="reviews">
              {{ wine.review_set.count }} Reviews
            </div>
            <div class="star-rating">
              {% for i in wine.average_rating|times %}
                <i class="fa fa-star" aria-hidden="true"></i>
              {%endfor%}
            </div>
          </a>
        </div>
        {% endfor %}

    </section>
    {% else %}
        <p>No wines are available.</p>
    {% endif %}

{% endblock %}